name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack --output out --configuration Release
    - name: Deploy
      run: dotnet nuget .\out\*.nupkg --api-key ${{ secrets.FSWORKER_NUGET }} --source https://api.nuget.org/v3/index.json
